[package]
name = "throttle"
version = "0.1.0"
edition = "2024"

[lints.rust]
dead_code = "allow"
unused_imports = "allow"

[dependencies]
async-trait = "0.1.89"
dashmap = "6.1.0"
tokio = { version = "1.48.0", features = ["full"] }
