[package]
name = "limiter"
version = "0.1.0"
edition = "2024"

[lints.rust]
dead_code = "allow"
unused_imports = "allow"

[dependencies]
async-trait = "0.1.89"
cache = { path = "../cache" }
throttle = { path = "../throttle" }
